import type { Metadata } from "next";
import { ReactNode } from "react";
import "./globals.css";
import Nav from "@/components/Header/Nav";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata: Metadata = {
  title: "ShopSy",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: ReactNode;
}>;

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Nav />
          <main className="mx-auto max-w-screen-xl p-4">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
